### ISSUE TITLE
Antibodies are not numbered

### ISSUE THREAD

**Issue by jadolfbr** [brennanaba/ImmuneBuilder#10]
**Is your feature request related to a problem? Please describe.**
The antibodies are numbered 1-N even though ANARCI is a requirement. 

**Describe the solution you'd like**
Antibodies should be output in a numbering scheme ideally, especially with ANARCI being used.

**Comment by brennanaba** [comment]
Hi Jared,

Antibodies are currently output using the IMGT numbering. Could you send me an example of a structure generated with ImmuneBuilder that is not numbered?

All the best,

Brennan

**Comment by jadolfbr** [comment]
My bad.  It looked like they were done 1-N and I didn’t see where it said
which scheme they were using.  I’ll take a look at the code, maybe an easy
way to add an option for alternatives. Go ahead and close this and
apologies for the mistake!

**Comment by brennanaba** [comment]
No worries, The ABodyBuilder2 class can take numbering_scheme as an argument.

**Comment by jadolfbr** [comment]
Awesome, so it would be just adding an arg parse arg to the parser and
passing down the line? Great! Thanks!
