### ISSUE TITLE
openmm.OpenMMException: Error loading CUDA module: CUDA_ERROR_UNSUPPORTED_PTX_VERSION (222)[BUG]

### ISSUE THREAD

**Issue by wjs20** [brennanaba/ImmuneBuilder#13]
Hi Brennan 

Thanks for making this amazing tool freely available. 

I ran into the above exception with an antibody I was trying to model. When it was trying to do the refinement step it was throwing the CUDA error above. 

I tracked down the problem to openmm. When I conda installed openmm, it installed cudatoolkit11.8 dependency by default. It seems like this toolkit was incompatible with my GPUs CUDA (11.6). When I specified 'conda install openmm cudatoolkit11.6' the error isn't thrown, at least on the initial sequence I was having issues with. 

I'm not sure if anyone else has had this issue, but I though I would leave this here in case anyone else encounters it.

Thanks!

**Comment by brennanaba** [comment]
Hi William,

Thanks a lot for your comments and for bringing this up. 

I have added a known issues section to the README and added a link to this issue in case anyone has the same problem in the future.

All the best,

Brennan
