### ISSUE TITLE
Documentation improvement of error estimates[FEATURE]

### ISSUE THREAD

**Issue by wjs20** [brennanaba/ImmuneBuilder#14]
Hi Brennan

I had a look at the error_estimates.npy file that is generated as part of the modelling process. It appears to be an array of shape (225,).

Maybe there is  some explanation of this in the paper that I have missed but I think it would be useful to add a line as to how to interpret this output in the repo.

Are these per residue estimates of error in terms of angstroms?

Thanks.

**Comment by brennanaba** [comment]
Hi William,

I think the error estimates in the error_estimates.npy file are in angstroms squared.

I calculate them as follows:
1. I align the structures generated by each of the four models. 
2. I find the "averaged structure" by averaging over the four aligned generated structures.
3. I calculate the distance between each of generated structures and the "averaged structure".
4. The final error estimate is the average of the square of these four distances for each residue.
5. The square root of this value is then saved in the B factor column of each PDB file.

The intuition behind it is that if 4 models trained on the same data generate very different structures then we expect those structures to be wrong. 

Hope that helps!!

All the best,

Brennan

**Comment by wjs20** [comment]
Thanks Brennan, that makes perfect sense.
