### ISSUE TITLE
Unnecessary logging disable

### ISSUE THREAD

**Issue by wjs20** [brennanaba/ImmuneBuilder#17]
in refine.py you have included these lines starting at line 6
```
import logging
logging.disable()
```
This caused some issues for me as it was preventing my own code from generating logs. Is there a reason for this being here? Do you think it could be removed?

**Comment by brennanaba** [comment]
Hi Will,

Sorry for the late response.

I added those lines to remove some messages from OpenMM. They don't affect the functionality of the code, so feel free to remove them in your local version.

All the best,

Brennan
