### ISSUE TITLE
[FEATURE] Embedding space

### ISSUE THREAD

**Issue by tony-res** [brennanaba/ImmuneBuilder#18]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Would it be possible for the model(s) to return an embedding space for the nanobodies?

**Describe the solution you'd like**

The goal would be to get an embedding/latent space vector that could be used by downstream models to predict things like binding affinity.

**Describe alternatives you've considered**

I've used ESM2 and OpenFold to get the embedding space, but thought this model might provide a better one for nanobodies.

**Additional context**

**Comment by brennanaba** [comment]
Hi Tony,

I have attached some code that will allow you to extract the embedding from the model. As it is an ensemble of 4 models, I am concatenating over the feature dimension. 

```python
from ImmuneBuilder import NanoBodyBuilder2 
import torch

pred = NanoBodyBuilder2()

sequence = {"H":'VKLLEQSGAEVKKPGASVKVSCKASGYSFTSYGLHWVRQAPGQRLEWMGWISAGTGNTKYSQKFRGRVTFTRDTSATTAYMGLSSLRPEDTAVYYCARDPYGGGKSEFDYWGQGTLVTVSS'}
nanobody = pred.predict(sequence)
embedding = torch.cat(nanobody.encodings, dim=-1)
```

I must say I have not had the chance to play around with these embeddings, so I have no idea how well it will work for downstream tasks. 

Best of luck!!!

Brennan

**Comment by tony-res** [comment]
I'll give it a try. Thanks so much!
