### ISSUE TITLE
Replicating Nanobody 7F5H

### ISSUE THREAD

**Issue by tony-res** [brennanaba/ImmuneBuilder#19]
I'm using the [Colab](https://github.com/brennanaba/ImmuneBuilder/blob/main/notebook/ImmuneBuilder.ipynb) notebook to find the prediction for RCSB PDB 7F5H (https://www.rcsb.org/structure/7F5H). The RCSB website says that the FASTA file is:

```
>7F5H_1|Chains A, B|SARS-CoV-2 Spike Receptor-Binding Domain (RBD)|Severe acute respiratory syndrome coronavirus 2 (2697049)
AGSPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTGTLEVLFQ
>7F5H_2|Chains C, D|Nanobody DL28|Vicugna pacos (30538)
GSSSQVQLQESGGGLVQAGGSLRLSCAASGSDFSSSTMGWYRQAPGKQREFVAISSEGSTSYAGSVKGRFTISRDNAKNTVYLQMNSLEPEDTAVYYCNVVDRWYDYWGQGTQVTVSAGRAGEQKLISEEDLNSAVDHHHHHH
```

I tried using that as `sequence_1` and `sequence_2` in the Colab notebook. 

When I review the output in pyMol, it appears that is correctly predicts only part of the nanobody structure. I admit that I haven't done this before so it's entirely possible that I am doing something wrong.

What I would like to do is to take experimentally confirmed 3D PDBs from RCSB nanobodies and use [TMScore](https://zhanggroup.org/TM-score/) to compare the prediction with the experimental structure. 

Could you give me an idea of how to do this?

<img width="297" alt="image" src="https://github.com/brennanaba/ImmuneBuilder/assets/124098125/e9f5e3e4-8f92-4f34-ab9f-0cef70abab09">

In the figure above the "green" is the whole nanobody and the "cyan" is the prediction. The prediction looks pretty close, but it only covers part of the nanobody structure.

**Comment by brennanaba** [comment]
Hi Tony,

Thanks for your interest in NanobodyBuilder2!!

NanobodyBuilder2 is a nanobody specific structure predictor. In the FASTA you have provided there is a nanobody and another protein (Covid RBD). As NanobodyBuilder2 only models nanobodies, it will ignore all other proteins and only model the nanobody. It also will only model one nanobody at a time. 

If you do want a model for the nanobody bound to the antigen you will need to use some other methods. As far as I am aware, currently available tools are not very successful at modelling nanobody-antigen complexes. Your best chance is probably [AlphaFold-Multimer](https://github.com/deepmind/alphafold) or to model them separately and then dock them.

I hope this makes sense.

All the best,

Brennan

**Comment by tony-res** [comment]
@brennanaba 

I was running another nanobody prediction and am seeing something similar but this time it's definitely missing part of the nanobody. 

MY `2G75.fasta` is this:
```
>H
QVQLQQSGAEVKKPGSSVKVSCKASGGTFSSYTISWVRQAPGQGLEWMGGITPILGIANYAQKFQGRVTITTDESTSTAYMELSSLRSEDTAVYYCARDTVMGGMDVWGQGTTVTVSSASTKGPSVFPLAPSSKSTSGGTSALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTSPLFVHHHHHHGDYKDDDDKG
```

If I do 

```
NanoBodyBuilder2 --fasta_file 2G75.fasta -vvv
```

Then the output is this:
```

                                                            \/       
        NanoBodyBuilder2                                   ⊂'l     
        A Method for Nanobody Structure Prediction          ll      
        Author: Brennan Abanades Kenyon                     llama~  
        Supervisor: Charlotte Deane                         || ||   
                                                            '' ''   

Sequence loaded succesfully.
Heavy chain is:
H: QVQLQQSGAEVKKPGSSVKVSCKASGGTFSSYTISWVRQAPGQGLEWMGGITPILGIANYAQKFQGRVTITTDESTSTAYMELSSLRSEDTAVYYCARDTVMGGMDVWGQGTTVTVSSASTKGPSVFPLAPSSKSTSGGTSALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTSPLFVHHHHHHGDYKDDDDKG
Running sequence through deep learning model...
Nanobody modelled succesfully, starting refinement.
Refinement finished. Saving final structure to NanoBodyBuilder2_output.pdb
```

If I pull up `NanoBodyBuilder2_output.pdb` into `pyMol` I only see the first part of the sequence:

```
QVQLQQSGAEVKKPGSSVKVSCKASGGTFSSYTISWVRQAPGQGLEWMGGITPILGIANYAQKFQGRVTITTDESTSTAYMELSSLRSEDTAVYYCARDTVMGGMDVWGQGTTVTVSS
```

So it is showing only the bold in the PDB file:

**QVQLQQSGAEVKKPGSSVKVSCKASGGTFSSYTISWVRQAPGQGLEWMGGITPILGIANYAQKFQGRVTITTDESTSTAYMELSSLRSEDTAVYYCARDTVMGGMDVWGQGTTVTVSS**ASTKGPSVFPLAPSSKSTSGGTSALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTSPLFVHHHHHHGDYKDDDDKG

The command-line output shows that it is reading everything, but the pyMol structure is just part of the sequence.

Am I doing something wrong?

Thanks in advance.
-Tony

**Comment by brennanaba** [comment]
Hi Tony,

The PDB entry [2G75](https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabdab/structureviewer/?pdb=2g75) contains the structure of two antibody Fabs. The Fab in antibodies is built from two constant and two variable domains (one of each for the heavy chain and one of each for the light chain). Nanobodies have a similar sequence and global structure to the variable domain of the heavy chain. The sequence you are feeding into NanobodyBuilder2 contains both the constant and variable domains of the heavy chain. NanobodyBuilder2 therefore truncates the sequence using [ANARCI](https://github.com/oxpig/ANARCI) to just the variable domain before feeding it into the deep learning model. 

I agree it is a bit confusing that it prints the whole sequence before truncating, I may try and fix this in the future.

I hope that helps and all the best,

Brennan

**Comment by tony-res** [comment]
Thanks so much for the explanation. That makes sense.

What I am working on at present is to run NanobodyBuilder against a list of nanobody PDBs from RCSB and then use TMScore/TMAlign to get a measure of the accuracy of the prediction. 

Is there a way that I can use ANARCI (or something different) to extract the part of the PDB file with just the variable region that is being predicted by NanoBodyBuilder?

**Comment by brennanaba** [comment]
Hi Tony,

Yes, you can use ANARCI for that. Here is an example of how you could do so.

```python
from anarci import number

seq = """QVQLQQSGAEVKKPGSSVKVSCKASGGTFSSYTISWVRQAPGQGLEWMGGITPILGIANYA
QKFQGRVTITTDESTSTAYMELSSLRSEDTAVYYCARDTVMGGMDVWGQGTTVTVSSASTKGPSVFPLAP
SSKSTSGGTSALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYIC
NVNHKPSNTKVDKKVEPKSCDKTSPLFVHHHHHHGDYKDDDDKG"""

numbering, chain = number(seq)
truncated_seq = "".join(x[1] for x in numbering if x[1]!= "-")
```

This issue is not related to ImmuneBuilder however, and should be opened on the [ANARCI repo](https://github.com/oxpig/ANARCI).

All the best,

Brennan
