### ISSUE TITLE
Inconsistency observed for each run

### ISSUE THREAD

**Issue by diyang1354** [brennanaba/ImmuneBuilder#24]
When I visualize the predicted structure, the coordinate for some atom may change after each separate run with the same mAb sequence, while most part of the structure remains the same. 
Do we have options to reproduce the result for different runs?
Thanks

**Comment by brennanaba** [comment]
Hi Diyang,

The inconsistency comes from the final energy minimisation run done with OpenMM to fix unphysical errors in the predicted structure. As far as I am aware, this is done using a stochastic optimisation method and there is no way of making it 100% consistent every time. 

In a way, you can take how inconsistent predictions in different regions are as a measure of how much you should trust the predicted structure in that region.

All the best,

Brennan
