### ISSUE TITLE
[FEATURE] Single-chain predictions in ABodyBuilder2

### ISSUE THREAD

**Issue by jahnzh** [brennanaba/ImmuneBuilder#26]
Since the vast majority of publicly available antibody sequences are single-chains, it would be of great interest to be able to predict their structures.

**Is your feature request related to a problem? Please describe.**
ABodyBuilder2 throws an error if given only a single input sequence.

**Describe the solution you'd like**
ABodyBuilder2 should predict individual chain structures when given only a single sequence.

**Describe alternatives you've considered**
Alternative is to use tools that do support single-chain predictions, such as IgFold.

**Comment by brennanaba** [comment]
Hi Jahn,

You are correct in that the vast majority of antibody sequence data is unpaired and that a single-chain predictor could be useful. However, what you are asking for would involve retraining all the models and would likely result in significantly worse perfomance. I currently do not have time to do this but will consider adding it in the future.

All the best,

Brennan
