### ISSUE TITLE
Overwriting temporary files when running multiple jobs.

### ISSUE THREAD

**Issue by OliverT1** [brennanaba/ImmuneBuilder#28]
**Describe the bug**
The temporary file side_chain_fix_tmp.pdb does not have a unique name and so is overwritten / deleted when running mulitple processes on the same environment. Results in:

[Errno 2] No such file or directory: 'side_chain_fix_tmp.pdb'

Or multiple different OpenMM errors.

**To Reproduce**
Run multiple ABB2 processes in the same environment.

**Comment by brennanaba** [comment]
Hi Ollie,

I hope you are doing well.

Good catch!! I am surprised this is causing you problems as the side chain fix code should be run very rarely. 

However, I have added a random id to the tmp file that should make this a lot less likely to happen. 

All the best,

Brennan
