### ISSUE TITLE
Setting seed for deterministic folding

### ISSUE THREAD

**Issue by tony-res** [brennanaba/ImmuneBuilder#30]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to reproduce the exact same structure each time I run ImmuneBuilder with the exact same input sequence.

**Describe the solution you'd like**

I think this would involve setting the random seed. Possibly in the OpenMM part, but maybe in other parts as well.

**Describe alternatives you've considered**

I'm not sure if there is another solution to getting a deterministic result. Maybe the PyTorch seed or the Numpy seed would be respected by the other scripts?

**Comment by brennanaba** [comment]
Hi Tony,

Thank you for reaching out and for your interest in ensuring reproducibility with ImmuneBuilder.

You are correct in noting that while the initial output from the deep learning model is deterministic, the subsequent energy minimization step with OpenMM introduces stochastic elements, resulting in variations in the final structure with each run.

Although OpenMM allows for setting a random seed, it does not guarantee that you will always get the same result. This is described [here](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.LangevinIntegrator.html#simtk.openmm.openmm.LangevinIntegrator.setRandomNumberSeed) in the documentation. Unfortunately, there is therefore not much I can do about this.

As an alternative, you may want to consider saving the deterministic output from ImmuneBuilder prior to the refinement step. This would allow you to use a different, deterministic refinement tool if reproducibility is a critical factor for your work. 

I hope this helps!!

All the best,

Brennan
