### ISSUE TITLE
Sequence provided as an A chain is not recognised as an A chain

### ISSUE THREAD

**Issue by mathias-grau** [brennanaba/ImmuneBuilder#31]
**The bug**
I have a problem wth the recognition of the alpha chain of a TCR. I encounter this issue : `Sequence provided as an A chain is not recognised as an A chain`. I have this issue for ~200 sequences like : 
- TCRalpha = "MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYDTSENNYYLFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDTAMYFCAFMKTGVGTSYDKVIFGPGTSLSVIPNIQNPDPAVYQLRDSKSSDKSVCLFTDFDSQTNVSQSKDSDVYITDKTVLDMRSMDFKSNSAVAWSNKSDFACANAFNNSIIPEDTFFPSPESSCDVKLVEKSFETDTNLNFQNLSVIGFRILLLKVAGFNLLMTLRLWSS"
- TCRbeta = "MVSRLLSLVSLCLLGAKHIEAGVTQFPSHSVIEKGQTVTLRCDPISGHDNLYWYRRVMGKEIKFLLHFVKESKQDESGMPNNRFLAERTGGTYSTLKVQPAELEDSGVYFCASSHPEGDVLTFGAGSRLTVLEDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWWVNGKEVHSGVSTDPQPLKEQPALNDSRYCLSSRLRVSATFWQNPRNHFRCQVQFYGLSENDEWTQDRAKPVTQIVSAEAWGRADCGFTSESYQQGVLSATILYEILLGKATLYAVLVSALVLMAMVKRKDSRG"

**To Reproduce**
Just run the **TCRBuilder2()** with these sequences.
`Traceback (most recent call last):
  File "/immunebuilder/test.py", line 6, in <module>
    tcr = predictor.predict(sequences)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.conda/envs/ImmuneBuilder/lib/python3.12/site-packages/ImmuneBuilder/TCRBuilder2.py", line 117, in predict
    numbered_sequences = number_sequences(sequence_dict, scheme=self.scheme)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.conda/envs/ImmuneBuilder/lib/python3.12/site-packages/ImmuneBuilder/sequence_checks.py", line 40, in number_sequences
    return {chain: number_single_sequence(seqs[chain], chain, scheme=scheme, allowed_species=allowed_species) for chain in seqs}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.conda/envs/ImmuneBuilder/lib/python3.12/site-packages/ImmuneBuilder/sequence_checks.py", line 21, in number_single_sequence
    assert numbered[0], f"Sequence provided as an {chain} chain is not recognised as an {chain} chain."
AssertionError: Sequence provided as an A chain is not recognised as an A chain.`

**Expected behavior**
Predict the structure of the TCR which work usually well

**Additional context**
I am using **IEDB** and **VDJdb** databases for my TCRs.

**Comment by brennanaba** [comment]
Hi Mathias,

Thank you for your interest in ImmuneBuilder. 

ImmuneBuilder uses [ANARCI](https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabpred/anarci/) to trim and number TCR sequences before predicting their structure. If a sequence is predicted to not be an alpha or beta chain, the error you encountered is raised. ANARCI predicts your alpha chain as delta, which is why that Exception is raised. 

All the best,

Brennan

**Comment by brennanaba** [comment]
Hi Mathias,

If you are sure you have alpha chains and do not want this assertion to be raised, you can comment out [the following line](https://github.com/brennanaba/ImmuneBuilder/blob/208078df2745940bb9c0470d871980c20641c8af/ImmuneBuilder/sequence_checks.py#L21). 

All the best,

Brennan
