### ISSUE TITLE
[FEATURE] Metrics/Model Confidence Evaluation

### ISSUE THREAD

**Issue by denizkavi** [brennanaba/ImmuneBuilder#32]
It would be useful to have some more quantitative measurements of the model's confidence or a comparable version of AlphaFold (i)pTM metrics to evaluate the model's confidence. I saw that the Colab notebook has a "pred_error" in the visualization but would be useful for me to have a number to compare against as well.

**Comment by brennanaba** [comment]
Hi Deniz,

Thanks for your interest in ImmuneBuilder. Error estimation in the ImmuneBuilder models is measured in a different way to AF2.  So don't expect to be able to directly compare them. If you want a number, you can get it from the b-factor column of the output PDB files.

Hope this helps!!

All the best,

Brennan
