### ISSUE TITLE
How to train NanoBodyBuilder2

### ISSUE THREAD

**Issue by jh2ee** [brennanaba/ImmuneBuilder#35]
Hi, I wonder how to train NanoBodyBuilder2.
For now, I'm trying to train your model by myself. But it's little bit hard work for me.
Your team didn't upload the training code so I have some problems to re-train the Model.

I want to use your model training my own datas. So if you don't mind, I ask you to provide the code.
I just want to reference yours.
Thank you.

**Comment by brennanaba** [comment]
Hi jh2ee,

The training code for ImmuneBuilder is currently not publicly available.

All the best,

Brennan
