### ISSUE TITLE
Immunebuilder gives different results for the final model if "antibody.save" is used instead of antibody.save_all"[BUG]

### ISSUE THREAD

**Issue by TheUG93** [brennanaba/ImmuneBuilder#37]
**Describe the bug**
Immunebuilder gives different results for the best model depending on whether antibody.save or antibody.save_all is used to save the structure results. This bug stems from an error in the antibody class save function where the rank is being passed to save_single_unrefined instead of the model index.

**To Reproduce**
Reproduce with the following sequenes:
Heavy chain: "QVQLEQSGPGLVAPSQRLSITCTVSGFSLTSYIVDWVRQSPGKGLEWLGVIWAGGSTGYNSALRSRLSITKSNSKSQVFLQMNSLQTDDTAIYYCASAAYYSYYNYDGFAYWGQGTLVTVSA"
Light chain: "ELVMTQTPATLSVTPGDSVSLSCRASQSISNHLHWYQQKSHESPRLLIKYASQSISGIPSRFSGSGSGTDFTLSINSVETEDFGMYFCQQSNSWPHTFGGGTKLEIK"

**Screenshots**
<img width="603" alt="Screenshot 2024-06-24 at 1 50 44 PM" src="https://github.com/brennanaba/ImmuneBuilder/assets/80774309/03e82926-45ab-4d32-9243-43a80c954200">
A comparison of the final model from the save function and the save_all function. I would expect complete overlap for the structures. 

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Python version 3.9
 - PyTorch version 1.13

**Comment by brennanaba** [comment]
Hi @TheUG93,

It looks like you may be right. Hopefully, I have fixed it now. Could you check you are getting what you would expect?

Thanks a lot for spotting it.

All the best,

Brennan

**Comment by TheUG93** [comment]
The final models match up now. Thanks!
