### ISSUE TITLE
low values in temperature column of pdb output from AbodyBuilder2

### ISSUE THREAD

**Issue by moduff** [brennanaba/ImmuneBuilder#40]
Not a bug I think, but just wondering about the values in AbodyBuilder2's output pdb temperature column.
My understanding is that typical values are between 0 and 100, but I'm seeing values that are consistently less than 1.

**Comment by brennanaba** [comment]
Hi Mike,

ImmuneBuilder predictions do not come with a temperature factor. That column is used to store the predicted uncertainty for each residue. How this is calculated is described in the ImmuneBuilder paper.

All the best,

Brennan
