### ISSUE TITLE
[BUG]saving the predicted model consumes too much memory

### ISSUE THREAD

**Issue by linuxonly801** [brennanaba/ImmuneBuilder#48]
**Describe the bug**
I want to use NanoBodyBuilder2 to predict a lot of structures (about 1000), but when I use a loop to iterate my sequences, something like the following code, the GPU memory increased every time i got a structure. And finally run OOM.

```python
from ImmuneBuilder import NanoBodyBuilder2

predictor = NanoBodyBuilder2()
for i in range(1000):
    sequence = {'H': 'QVQLVESGGGLVQPGESLRLSCAASGSIFGIYAVHWFRMAPGKEREFTAGFGSHGSTNYAASVKGRFTMSRDNAKNTTYLQMNSLKPADTAVYYCHALIKNELGFLDYWGPGTQVTVSS'}

    antibody = predictor.predict(sequence)
    antibody.save("test.pdb")
```
![2024-12-13_23-59](https://github.com/user-attachments/assets/02371b92-3c34-4514-831e-b7f0a521dc2c)

But, if i modify the code like below, the GPU memory stays the same for predicting the result. But when running ab.save(f"test{cnt}.pdb"), the GPU memory increases very fast, and finally got OOM.
```python
from ImmuneBuilder import NanoBodyBuilder2

predictor = NanoBodyBuilder2()
results = []
for i in range(1000):
    sequence = {'H': 'QVQLVESGGGLVQPGESLRLSCAASGSIFGIYAVHWFRMAPGKEREFTAGFGSHGSTNYAASVKGRFTMSRDNAKNTTYLQMNSLKPADTAVYYCHALIKNELGFLDYWGPGTQVTVSS'}

    antibody = predictor.predict(sequence)
    results.append(antibody)

cnt = 0
for ab in results:
    ab.save(f"test{cnt}.pdb")
    cnt += 1
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.12
 - PyTorch version: 2.5

**Comment by brennanaba** [comment]
Hi Linuxonly,

Thank you for your interest in using NanoBodyBuilder2. 

The save function is the where refinement of the predicted structure with OpenMM happens. It seems like your installation of OpenMM is not releasing GPU memory after completion. I suspect there is a bug in your version of OpenMM. 

Hope that helps!!

All the best,

Brennan
